# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.ssh.insert_key = false
    config.ssh.private_key_path = "~/.ssh/vagrant/insecure_private_key"

    # 共通設定
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "8192"
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    end

    config.vm.synced_folder "../.share/torrent", "/home/vagrant/torrent"
    config.vm.synced_folder "./.share", "/share"

    # router
    MAX_OF_ROUTER = (ENV["MAX_OF_ROUTER"] || 1).to_i
    (1..MAX_OF_ROUTER).each do |id|
        config.vm.define "router#{id}" do |router|
            router.vm.hostname = "client#{id}"
            router.vm.network "private_network", ip: "192.168.61.#{100+id}", virtualbox__intnet: true
            router.vm.network "private_network", ip: "192.168.62.#{100+id}", virtualbox__intnet: true
            router.vm.network "public_network", bridge: "enp6s0"

            router.vm.provision :shell, path: "../bash/common.sh"
            router.vm.provision :shell, path: "../bash/install_cefore.sh"
            # ceforeの設定
            router.vm.provision :shell, path: "../bash/cefore_setting.sh"
            router.vm.provision :shell, run: "always", path: "../bash/buffa_tune.sh"
        end
    end
end